### PR TITLE
Implemented exception handling to agent

### PR DESCRIPTION
**Pull request by osean-man**
Running into an error where the return was None, an exception would crash the agent. Implemented a fix with exception handling.

### CODE REVIEW

**Comment by i128** [comment]
Interesting. I appreciate the PR. Do you recall what situation this happened in? Like was it in-between agent call backs and the user killed/stopped a task/job?

**Comment by osean-man** [comment]
I loaded the following hash: c05e35377b5a31f428ccda9724a9dfbd0c5d71dccac691228d803c78e2e8da29 (as an upload).

It was just a test and I got this from the NahamStore (TryHackMe room). It's a raw sha-256 (HC mode 1400). The agent crashed on the TypeError as the json.loads received a NoneType. I suppose rather than a try block it could just default return an empty array instead. This was just my quick fix while trying out Hashview. 

If you need to reproduce, I did the following:

- Fresh install of hashview (note: I did have an issue with SQLAlchemy/collation that I had to solve with this https://tecadmin.net/resolved-unknown-collation-utf8mb4_0900_ai_ci/)
- Created an agent and approved
- Created a job for the agent
- Agent crashed on the line numbers this PR is for with a TypeError (NoneType not supported...).

**Comment by i128** [comment]
Awesome, i appreciate the feedback, I will attempt to reproduce. 
Regarding the block try vs returning an empty array, i almost prefer the error so that i can handle those use cases. Because in theory that value should never be none. But i agree this shouldnt be happening in the first place.

**Comment by osean-man** [comment]
Agreed. No problem. I figured the program should continue rather than die so I used https://docs.python.org/3/library/contextlib.html#contextlib.suppress to handle the TypeError specifically. 

Great work on the project, I'm looking forward to using it.

**Comment by i128** [comment]
Merged, sorry for the delay

**Pull request merged**
